### ISSUE TITLE
GPS Module Question

### ISSUE THREAD

**Issue by smartbadger** [johan-m-o/BikeTracker#1]
Hi, 

This is a really cool project. I'm trying to work on something similar but a bit more integrated into my e-bike. I was curious, what was the rationale for having a separate GPS module when the location can be obtained from the MKR 1400 board? Was the integrated service unreliable or was it another reason?

Thanks!

**Comment by johan-m-o** [comment]
Accuracy, that's all... The device uses the MKR board if a GPS signal can't be obtained.

**Comment by smartbadger** [comment]
Awesome, thanks for the fast reply!

**Comment by johan-m-o** [comment]
No worries. There are also a couple of extra features using the GPS, such as being able to tell what direction the device is moving and how fast.

**Comment by smartbadger** [comment]
I'll have to review the docs for that module, sounds like a useful feature!
